### ISSUE TITLE
Trying gtfs2lc with EMT data from Madrid

### ISSUE THREAD

**Issue by allaves** [linkedconnections/gtfs2lc#1]
After installing with "npm install" the modules csv, level, n3, q and unzip, I started the execution of gtfs2lc at 10:35 am: ./gtfs-csv2connections path/to/data/transitEMT.zip > path/to/data/emtConnections.ttl

Let me know if you want to access the EMT GTFS data.

After completing some steps, at 4:15 pm it crashed with the following message:
Draining Agencies
Transforming Calendar
Transforming CalendarDates
Transforming Frequencies
Transforming Routes
Draining Shapes and Shape Segments
Draining Stops
Transforming Stop Times
Transforming Trips
Transforming GTFS store to arrival/departures
FATAL ERROR: JS Allocation failed - process out of memory
Aborted (core dumped)

The system crash message is titled "nodejs crashed with SIGABRT in v8::Function::Call()". A crash report was created at /var/crash/ (~90MB).

The following folders were created at the execution path: arrivals, dates, departures, and stop_times. They all contain .ldb documents and a LOG, among others. Let me know if you need to see any of the logs.

I am using Ubuntu 14.04.1 LTS "Trusty Tahr", running on a Toshiba Portégé with Intel CORE i7 and 16GB RAM.

**Comment by pietercolpaert** [comment]
Thanks for the issue.

I will push updates in a couple of days which should remove all in memory optimism from my part. These updates will handle the conversions a bit more structured:
 1. gtfs → gtfs rdf json-ld objects
 2. gtfs rdf json-ld object → store to key-val of choice using an abstraction layer (leveldb by default but maybe other databases give faster results)
 3. from the GTFS json-ld object store abstraction layer → Arrivals / Departures
 4. Arrivals / Departures → store using an abstraction layer
 5. Arrival / Departures from abstraction layer → linked connections (yay)

I've looked into existing tooling but can't seem to find anything that can help me with 1 or more steps

**Comment by pietercolpaert** [comment]
Hi @allaves,

Currently, @brechtvdv has written his own script to transform gtfs to arrivals/departures, and there's another repo that transforms arrivals/departures to linked connections. Can you test this again with the documentation you can now find in the README, or the documentation written in this repo: https://github.com/linkedconnections/server.js#from-a-gtfs-file?

Thank you in advance!

Pieter

**Comment by allaves** [comment]
Hi,

I tried yesterday to convert the GTFS data from EMT Madrid to Linked Connections. First of all, the documentation is a bit confusing because forces you to jump between Github repos. Having the documentation and the code in one single repository would help.

Following https://github.com/linkedconnections/server.js#from-a-gtfs-file, I started with "1. Use gtfs2arrdep script to transform a GTFS file into arrivals/departures". I downloaded and installed Composer in my Ubuntu 14.04 using `sudo curl -sS https://getcomposer.org/installer | php`, sudo because of permission problems with certificates. And then, I installed Composer with `php composer.phar install`. It should be specified if the MySQL requirement is for the server or the client. I assume it is the server in this case, but I installed both. Afterwards, I filled my credentials in `db-config.php` and run `scripts/init.sh .../Datos_GTFS/ftp/emt/transitEMT.zip`. This was running for more than two hours and I am not sure if it finished executing the database load script, but I had to kill the process because it was time to leave. Next, the log message I got:

```
allaves@allaves-portege:~/git/gtfs2arrdep$ ./scripts/init.sh .../Datos_GTFS/ftp/emt/transitEMT.zip 
                                                         
  [Doctrine\DBAL\Exception\DriverException]              
  An exception occured in driver: could not find driver  
                                       
  [Doctrine\DBAL\Driver\PDOException]  
  could not find driver                
                                      
  [PDOException]         
  could not find driver  
                         
orm:schema-tool:update [--complete] [--dump-sql] [--force]

Archive:  .../Datos_GTFS/ftp/emt/transitEMT.zip
  inflating: /tmp/gtfs2arrdep/agency.txt  
  inflating: /tmp/gtfs2arrdep/calendar.txt  
  inflating: /tmp/gtfs2arrdep/calendar_dates.txt  
  inflating: /tmp/gtfs2arrdep/frequencies.txt  
  inflating: /tmp/gtfs2arrdep/routes.txt  
  inflating: /tmp/gtfs2arrdep/shapes.txt  
  inflating: /tmp/gtfs2arrdep/stops.txt  
  inflating: /tmp/gtfs2arrdep/stop_times.txt  
  inflating: /tmp/gtfs2arrdep/trips.txt  
PHP Fatal error:  Uncaught exception 'Doctrine\ORM\ORMException' with message 'Entity of type Agency is missing an assigned ID for field  'agencyId'. The identifier generation strategy for this entity requires the ID field to be populated before EntityManager#persist() is called. If you want automatically generated identifiers instead you need to adjust the metadata mapping accordingly.' in /home/allaves/git/gtfs2arrdep/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php:86
Stack trace:
#0 /home/allaves/git/gtfs2arrdep/vendor/doctrine/orm/lib/Doctrine/ORM/Id/AssignedGenerator.php(58): Doctrine\ORM\ORMException::entityMissingAssignedIdForField(Object(Agency), 'agencyId')
#1 /home/allaves/git/gtfs2arrdep/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(851): Doctrine\ORM\Id\AssignedGenerator->generate(Object(Doctrine\ORM\EntityManager), Object(Agency))
#2 /home/allaves/git/gtfs2arrdep/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1627): Doctrine\ORM\UnitOfWork->persistNew(Object(Doctrine\ORM\Mapping\ClassMetadata), Ob in /home/allaves/git/gtfs2arrdep/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php on line 86
PHP Fatal error:  Uncaught exception 'PDOException' with message 'could not find driver' in /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=127....', 'root', 'pass', Array)
#1 /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(45): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=127....', 'root', 'pass', Array)
#2 /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', 'pass', Array)
#3 /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1166): Doctrine\DBAL\Connection->connect()
#4 /home/allaves/git/gtfs2arrdep/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(330): Doctrine\DBAL\Connection->beginTransaction()
#5 /home/allaves/git/gtfs2arrdep in /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115
PHP Fatal error:  Uncaught exception 'PDOException' with message 'could not find driver' in /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=127....', 'root', 'pass', Array)
#1 /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(45): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=127....', 'root', 'pass', Array)
#2 /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', 'pass', Array)
#3 /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1166): Doctrine\DBAL\Connection->connect()
#4 /home/allaves/git/gtfs2arrdep/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(330): Doctrine\DBAL\Connection->beginTransaction()
#5 /home/allaves/git/gtfs2arrdep in /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115
PHP Fatal error:  Uncaught exception 'PDOException' with message 'could not find driver' in /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=127....', 'root', 'pass', Array)
#1 /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(45): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=127....', 'root', 'pass', Array)
#2 /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', 'pass', Array)
#3 /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1166): Doctrine\DBAL\Connection->connect()
#4 /home/allaves/git/gtfs2arrdep/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(330): Doctrine\DBAL\Connection->beginTransaction()
#5 /home/allaves/git/gtfs2arrdep in /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115
```

**Comment by brechtvdv** [comment]
Hi

MySQL is only required for the gtfs2arrdep project. Server.js works (for now) only with MongoDB. 
I don't know if it's a good idea to combine the code in one repository, because they're written in a different language (PHP and Javascript). @pietercolpaert what do you think?

Do you have php5-mysql installed?
```bash
sudo apt-get install php5-mysql
```

**Comment by pietercolpaert** [comment]
Certainly not a good idea to combine both projects indeed. It is however a good idea for the long term to work in this repository on a single javascript toolkit for GTFS to connections

**Comment by allaves** [comment]
Now, I have installed php5-mysql. This is the output of the second iteration:
```
allaves@allaves-portege:~/git/gtfs2arrdep$ ./scripts/init.sh .../Datos_GTFS/ftp/emt/transitEMT.zip
CREATE TABLE frequencies (id INT AUTO_INCREMENT NOT NULL, tripId VARCHAR(255) NOT NULL, startTime TIME NOT NULL, endTime TIME NOT NULL, headwaySecs INT NOT NULL, exactTimes INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE trips (tripId VARCHAR(255) NOT NULL, routeId VARCHAR(255) NOT NULL, serviceId VARCHAR(255) NOT NULL, tripHeadSign VARCHAR(255) DEFAULT NULL, tripShortName VARCHAR(255) DEFAULT NULL, directionId VARCHAR(255) DEFAULT NULL, blockId VARCHAR(255) DEFAULT NULL, shapeId VARCHAR(255) DEFAULT NULL, wheelchairAccessible INT DEFAULT NULL, bikesAllowed INT DEFAULT NULL, PRIMARY KEY(tripId)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE routes (routeId VARCHAR(255) NOT NULL, agencyId VARCHAR(255) DEFAULT NULL, routeShortName VARCHAR(255) NOT NULL, routeLongName VARCHAR(255) NOT NULL, routeDesc VARCHAR(255) DEFAULT NULL, routeType INT NOT NULL, routeUrl VARCHAR(255) DEFAULT NULL, routeColor VARCHAR(255) DEFAULT NULL, routeTextColor VARCHAR(255) DEFAULT NULL, PRIMARY KEY(routeId)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE stoptimes (id INT AUTO_INCREMENT NOT NULL, tripId VARCHAR(255) NOT NULL, arrivalTime TIME NOT NULL, departureTime TIME NOT NULL, stopId VARCHAR(255) NOT NULL, stopSequence INT NOT NULL, maxStopSequence INT NOT NULL, arrivalAfterMidnight TINYINT(1) NOT NULL, departureAfterMidnight TINYINT(1) NOT NULL, stopHeadsign VARCHAR(255) DEFAULT NULL, pickupType VARCHAR(255) DEFAULT NULL, dropOffType INT DEFAULT NULL, shapeDistTraveled VARCHAR(255) DEFAULT NULL, timepoint INT DEFAULT NULL, INDEX STOP_TIMES_STOP_ID_IND (stopId), INDEX STOP_TIMES_DEPARTURE_TIME_IND (departureTime), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE agency (agencyId VARCHAR(255) NOT NULL, agencyName VARCHAR(255) NOT NULL, agencyUrl VARCHAR(255) NOT NULL, agencyTimezone VARCHAR(255) NOT NULL, agencyLang VARCHAR(255) DEFAULT NULL, agencyPhone VARCHAR(255) DEFAULT NULL, agencyFareUrl VARCHAR(255) DEFAULT NULL, PRIMARY KEY(agencyId)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE stops (stopId VARCHAR(255) NOT NULL, stopCode VARCHAR(255) DEFAULT NULL, stopName VARCHAR(255) NOT NULL, stopDesc VARCHAR(255) DEFAULT NULL, stopLat DOUBLE PRECISION NOT NULL, stopLon DOUBLE PRECISION NOT NULL, zoneId VARCHAR(255) DEFAULT NULL, stopUrl VARCHAR(255) DEFAULT NULL, locationType VARCHAR(255) DEFAULT NULL, parentStation VARCHAR(255) DEFAULT NULL, stopTimezone VARCHAR(255) DEFAULT NULL, wheelchairBoarding INT DEFAULT NULL, INDEX STOPS_STOP_CODE_IND (stopCode), INDEX STOPS_STOP_NAME_IND (stopName), PRIMARY KEY(stopId)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE calendarDates (id INT AUTO_INCREMENT NOT NULL, serviceId VARCHAR(255) NOT NULL, date DATE NOT NULL, exceptionType INT NOT NULL, INDEX CALENDAR_DATES_SERVICE_ID_IND (serviceId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE calendars (serviceId VARCHAR(255) NOT NULL, monday INT NOT NULL, tuesday INT NOT NULL, wednesday INT NOT NULL, thursday INT NOT NULL, friday INT NOT NULL, saturday INT NOT NULL, sunday INT NOT NULL, startDate DATE NOT NULL, endDate DATE NOT NULL, PRIMARY KEY(serviceId)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

Updating database schema...
Database schema updated successfully! "8" queries were executed
Archive:  .../Datos_GTFS/ftp/emt/transitEMT.zip
  inflating: /tmp/gtfs2arrdep/agency.txt  
  inflating: /tmp/gtfs2arrdep/calendar.txt  
  inflating: /tmp/gtfs2arrdep/calendar_dates.txt  
  inflating: /tmp/gtfs2arrdep/frequencies.txt  
  inflating: /tmp/gtfs2arrdep/routes.txt  
  inflating: /tmp/gtfs2arrdep/shapes.txt  
  inflating: /tmp/gtfs2arrdep/stops.txt  
  inflating: /tmp/gtfs2arrdep/stop_times.txt  
  inflating: /tmp/gtfs2arrdep/trips.txt  
PHP Fatal error:  Uncaught exception 'Doctrine\ORM\ORMException' with message 'Entity of type Agency is missing an assigned ID for field  'agencyId'. The identifier generation strategy for this entity requires the ID field to be populated before EntityManager#persist() is called. If you want automatically generated identifiers instead you need to adjust the metadata mapping accordingly.' in /home/allaves/git/gtfs2arrdep/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php:86
Stack trace:
#0 /home/allaves/git/gtfs2arrdep/vendor/doctrine/orm/lib/Doctrine/ORM/Id/AssignedGenerator.php(58): Doctrine\ORM\ORMException::entityMissingAssignedIdForField(Object(Agency), 'agencyId')
#1 /home/allaves/git/gtfs2arrdep/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(851): Doctrine\ORM\Id\AssignedGenerator->generate(Object(Doctrine\ORM\EntityManager), Object(Agency))
#2 /home/allaves/git/gtfs2arrdep/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1627): Doctrine\ORM\UnitOfWork->persistNew(Object(Doctrine\ORM\Mapping\ClassMetadata), Ob in /home/allaves/git/gtfs2arrdep/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php on line 86
Created 4647 stops
Created 207 routes
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'routeId' cannot be null' in /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL)
#1 /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(165): Doctrine\DBAL\Driver\PDOStatement->execute(NULL)
#2 /home/allaves/git/gtfs2arrdep/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php(279): Doctrine\DBAL\Statement->execute()
#3 /home/allaves/git/gtfs2arrdep/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(966): Doctrine\ORM\Persisters\BasicEntityPersister->executeInserts()
#4 /home/allaves/git/gtfs2arrdep/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(335): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /home/allaves/git/gtfs2arrde in /home/allaves/git/gtfs2arrdep/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 112
```
Apparently, the script is still running but nothing happens. Should I leave it running or is it designed to stop after "fatal errors"?

**Comment by pietercolpaert** [comment]
Can you give us a link to the EMT data? Seems like there's a small bug in the PHP which relies on an agency_id being set in agency.txt

**Comment by brechtvdv** [comment]
I'm making a much faster and direct way to generate connections: https://github.com/brechtvdv/gtfs2connections (there's still no support for calendars)
Can you send me the EMT data, so I can test it?

**Comment by allaves** [comment]
I share the (confidential) dataset with Pieter last week and I thought you already have it. I will forward you the email.

**Comment by pietercolpaert** [comment]
@allaves My bad! Missed the e-mail apparently... Will share you some more details about the demo very soon! It's getting there :)

**Comment by brechtvdv** [comment]
Thanks!

**Comment by pietercolpaert** [comment]
Hi @allaves - I just reworked this entire repository. It should now be possible to create a stream of connections for EMT. Would you still find time to test this?

Thank you in advance!

**Comment by pietercolpaert** [comment]
Closing for now, not to confuse anyone else with an issue relating to the old way :)

**Comment by pietercolpaert** [comment]
Just found the time to retry this. Apparently EMT uses frequencies, which is not yet implemented. Will need to invest more time in fixing this. Will make a separate issue.
