### ISSUE TITLE
Fatal crash on GTFS files depending on calendar_dates

### ISSUE THREAD

**Issue by Bertware** [linkedconnections/gtfs2lc#55]
If a lot of calendar entries are present in a GTFS file for the same trip id, the script will crash. This is caused in [`calendar.js:88`](https://github.com/linkedconnections/gtfs2lc/blob/master/lib/services/calendar.js#L88).

```

RangeError: Maximum call stack size exceeded
    at RegExp.test (<anonymous>)
    at expandFormat (/home/bert/Desktop/linked-connections-server/node_modules/moment/moment.js:627:48)
    at configFromStringAndFormat (/home/bert/Desktop/linked-connections-server/node_modules/moment/moment.js:2407:18)
    at prepareConfig (/home/bert/Desktop/linked-connections-server/node_modules/moment/moment.js:2575:13)
    at createFromConfig (/home/bert/Desktop/linked-connections-server/node_modules/moment/moment.js:2544:44)
    at createLocalOrUTC (/home/bert/Desktop/linked-connections-server/node_modules/moment/moment.js:2631:16)
    at createLocal (/home/bert/Desktop/linked-connections-server/node_modules/moment/moment.js:2635:16)
    at hooks (/home/bert/Desktop/linked-connections-server/node_modules/moment/moment.js:12:29)
    at StreamIterator.next (/home/bert/Desktop/linked-connections-server/node_modules/gtfs2lc/lib/StreamIterator.js:34:56)
    at CalendarToServices._processCalendarDates (/home/bert/Desktop/linked-connections-server/node_modules/gtfs2lc/lib/services/calendar.js:86:33)
    at /home/bert/Desktop/linked-connections-server/node_modules/gtfs2lc/lib/services/calendar.js:88:14
    at StreamIterator.next (/home/bert/Desktop/linked-connections-server/node_modules/gtfs2lc/lib/StreamIterator.js:36:5)
    at CalendarToServices._processCalendarDates (/home/bert/Desktop/linked-connections-server/node_modules/gtfs2lc/lib/services/calendar.js:86:33)
    at /home/bert/Desktop/linked-connections-server/node_modules/gtfs2lc/lib/services/calendar.js:88:14
    at StreamIterator.next (/home/bert/Desktop/linked-connections-server/node_modules/gtfs2lc/lib/StreamIterator.js:36:5)
    at CalendarToServices._processCalendarDates (/home/bert/Desktop/linked-connections-server/node_modules/gtfs2lc/lib/services/calendar.js:86:33)

```

Example GTFS file (Too big for git): https://filehost.net/89f4172762918be7

I am aware that this GTFS file does not follow GTFS best practices (calendars.txt is not used, but instead calendar_dates is used), but if mass adoption is to follow, it might be best to support this.

**Comment by pietercolpaert** [comment]
Did you try this with the levelstore or with the memstore?

**Comment by pietercolpaert** [comment]
Can you retest with v0.8.2? I did not encounter the issue on my machine. The memory consumption appears to be stable at around 200MB and doesn’t increase with this GTFS file.
